### PR TITLE
Bug fixes, code cleanup, and particle spawning on size restoration.

### LINKED ISSUE #6: Incompatibility with Liquid Enchanting
There is an incompatibility with [Liquid Enchanting](https://minecraft.curseforge.com/projects/liquid-enchanting) where if you put any potion from this mod onto an armor using Liquid Enchanting it will create a storm of smoke particles, making the game unplayable.

### PR DESCRIPTION
**Pull request by Phylogeny**
Fixes #6. This PR:
1. Prevents log-spamming NPEs thrown when attempting to send packets to tracked players from the client. That can only be done server-side.
2. Fixes bug where particles are spawned every 30 seconds, rather than only when the player is resized.
3. Removes potential for null pointer access when attempting to retrieve players in packet payloads.
4. Allows particles to spawn when restoring player size, rather than just on initial resizing.
5. Refactors some methods, and merges shrinking/growth packets to a single packet, to prevent unnecessary code duplication.

### CODE REVIEW

**Comment by Phylogeny** [comment]
@CammiePone Any questions about this PR?

**Comment by CammiePone** [comment]
Is there a possibility I can talk to you on Discord, Phylogony?

**Comment by Phylogeny** [comment]
Yeah, no problem.

**Comment by CammiePone** [comment]
Camellias#2345

**Pull request merged**
